# Generated by Django 4.2 on 2023-10-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_reactiontoreply_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reaction',
            new_name='reaction_type',
        ),
    ]
