# Generated by Django 4.2 on 2023-10-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_reaction_reaction_reaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'Твит', 'verbose_name_plural': 'Твиты'},
        ),
    ]
